"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import sys
from pathlib import Path
from datetime import timedelta

# --- BASE_DIR (Aapke screenshot ke hisaab se) ---
# settings.py 'backend/' folder ke andar hai
# 'parent' hai root 'AI STUDY HUB'
BASE_DIR = Path(__file__).resolve().parent.parent 

# 'apps' folder ko Python ke search path mein add kar rahe hain
sys.path.append(str(BASE_DIR / 'apps'))


SECRET_KEY = 'django-insecure-gnji_y%1(dlb)&(6i=)&n%j*^0^m3#_vtv2h_nraf6n$u^g6yc'
DEBUG = True

# Aap ise Vercel par host karoge, isliye abhi localhost rakha hai
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # 'your-vercel-app-name.vercel.app', # Jab Vercel par host hoga
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'accounts', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Yeh CommonMiddleware se upar hona chahiye
    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls' # Yeh 'backend/urls.py' ko point karega

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # <-- YEH KHAALI RAHEGA
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'college_hub_db',
        'USER': 'root',
        'PASSWORD': '123456', # <-- Yahaan naya password daal dein
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- YEH LINE MISSING THI ---
# Django ko batayein ki humara CustomUser model use karna hai
AUTH_USER_MODEL = 'accounts.CustomUser'
# --- Yahaan tak ---

# --- CORS Settings ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
    "http://127.0.0.1:5500",
    "null", # Local file (file://) ke liye
    # "https://your-vercel-app-name.vercel.app", # Yahaan Vercel ka URL daalein
]


# --- YEH POORA SECTION MISSING THA ---
# --- REST Framework aur Simple JWT ki settings ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}
# --- Yahaan tak ---

# --- Media Files (Uploaded Images) Settings ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # 'media' folder root mein banega